In [257]:
import pandas as pd
import numpy as np


#original upload

In [258]:
#upload to the G-Drive
from google.colab import drive

In [259]:
import pandas as pd
data = pd.read_csv('/content/gdrive/My Drive/Project/hybrid/model/IPG_database.csv')
data.head(10)

Sr.NO.  I.D      IPG       Peak    Valley     Der_1    Peak_1  Valley_1  \
0       1  D71  0.373456  0.775640  0.016981 -0.005604  0.075607 -0.067647   
1       2  D72  0.376159  0.775258  0.018267 -0.002466  0.074919 -0.069028   
2       3  D73  0.411709  0.773179  0.018063 -0.000346  0.076127 -0.066614   
3       4  D74  0.402832  0.777636  0.021748 -0.000422  0.074561 -0.067598   
4       5  D75  0.409502  0.775560  0.013169 -0.003394  0.075800 -0.065322   
5       6  D76  0.412412  0.777192  0.016080 -0.003718  0.074918 -0.067613   
6       7  D77  0.425550  0.776366  0.018781 -0.002518  0.075091 -0.064897   
7       8  D81  0.152366  0.294503  0.017998 -0.004177  0.058669 -0.039963   
8       9  D82  0.152222  0.295061  0.018319 -0.003806  0.059550 -0.039249   
9      10  D83  0.152543  0.295700  0.017895 -0.039249  0.059832 -0.039570   

      Der_2  Peak_1.1  Valley_1.1  LVET         SV  
0 -0.000784  0.026924   -0.016629    40  65.324158  
1 -0.000211  0.025750   -0.017204    40  64.730043  
2 -0.000286  0.026179   -0.017478    40  65.774037  
3 -0.000222  0.026174   -0.018720    40  64.420698  
4 -0.000288  0.026178   -0.016810    40  65.491376  
5 -0.000457  0.027030   -0.016366    40  64.728727  
6 -0.000294  0.026427   -0.016836    40  64.878833  
7 -0.001234  0.025190   -0.021587    50  63.362841  
8 -0.001295  0.026049   -0.021596    50  64.314418  
9 -0.001242  0.027153   -0.021597    50  64.618907

In [260]:
data.shape

(53, 13)

#synthetic data gen

In [294]:
pip install sdv

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [295]:
from sdv.tabular import GaussianCopula
model_synthetic = GaussianCopula()
model_synthetic.fit(data)

In [296]:
new_data = model_synthetic.sample(num_rows=500)
new_data.head()

Sr.NO.    I.D      IPG       Peak    Valley     Der_1    Peak_1  Valley_1  \
0      33   D128  0.200721  0.404174  0.009054 -0.006301  0.066048 -0.048660   
1       9    D87  0.271155  0.652081  0.011551 -0.025120  0.066763 -0.049594   
2      33  D1110  0.228762  0.475656  0.009449 -0.055991  0.066943 -0.049691   
3      43    D87  0.192840  0.511973  0.009552 -0.047504  0.067025 -0.049624   
4      14   D126  0.212300  0.395159  0.009089 -0.045708  0.067125 -0.049998   

      Der_2  Peak_1.1  Valley_1.1  LVET         SV  
0 -0.000844  0.028526   -0.019521    50  63.205396  
1 -0.000847  0.028527   -0.019698    40  63.503881  
2 -0.000846  0.028783   -0.020448    40  59.745951  
3 -0.000845  0.028668   -0.020762    40  61.829199  
4 -0.000853  0.028939   -0.021323    40  64.594981

In [297]:
print(new_data.shape)

(500, 13)


In [298]:
from sdv.evaluation import evaluate
evaluate(new_data, data)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


0.444204507563621

In [299]:
evaluate(new_data, data, metrics=['CSTest', 'KSTest'])

0.7994056603773585

In [300]:
#evaluate(new_data, data, metrics=['KSTest'], aggregate=False)

In [301]:
print(type(new_data))
df = new_data

<class 'pandas.core.frame.DataFrame'>


In [302]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


#Download Synthetic here

In [ ]:
from google.colab import files
new_data.to_csv('database.csv') 
files.download('database.csv')

#uploading and pre-pro

In [303]:
#upload to the G-Drive
#from google.colab import drive
#drive.mount('/content/gdrive')

In [304]:
#import pandas as pd
#df = pd.read_csv('/content/gdrive/My Drive/Project/hybrid/model/database_5000.csv')
#df.shape

In [305]:
df.head()

Sr.NO.    I.D      IPG       Peak    Valley     Der_1    Peak_1  Valley_1  \
0      33   D128  0.200721  0.404174  0.009054 -0.006301  0.066048 -0.048660   
1       9    D87  0.271155  0.652081  0.011551 -0.025120  0.066763 -0.049594   
2      33  D1110  0.228762  0.475656  0.009449 -0.055991  0.066943 -0.049691   
3      43    D87  0.192840  0.511973  0.009552 -0.047504  0.067025 -0.049624   
4      14   D126  0.212300  0.395159  0.009089 -0.045708  0.067125 -0.049998   

      Der_2  Peak_1.1  Valley_1.1  LVET         SV  
0 -0.000844  0.028526   -0.019521    50  63.205396  
1 -0.000847  0.028527   -0.019698    40  63.503881  
2 -0.000846  0.028783   -0.020448    40  59.745951  
3 -0.000845  0.028668   -0.020762    40  61.829199  
4 -0.000853  0.028939   -0.021323    40  64.594981

In [306]:
x = df.drop(["Sr.NO.","I.D","SV"],axis=1)

In [307]:
x.head()

IPG       Peak    Valley     Der_1    Peak_1  Valley_1     Der_2  \
0  0.200721  0.404174  0.009054 -0.006301  0.066048 -0.048660 -0.000844   
1  0.271155  0.652081  0.011551 -0.025120  0.066763 -0.049594 -0.000847   
2  0.228762  0.475656  0.009449 -0.055991  0.066943 -0.049691 -0.000846   
3  0.192840  0.511973  0.009552 -0.047504  0.067025 -0.049624 -0.000845   
4  0.212300  0.395159  0.009089 -0.045708  0.067125 -0.049998 -0.000853   

   Peak_1.1  Valley_1.1  LVET  
0  0.028526   -0.019521    50  
1  0.028527   -0.019698    40  
2  0.028783   -0.020448    40  
3  0.028668   -0.020762    40  
4  0.028939   -0.021323    40

In [308]:
y = df[["SV"]]

In [309]:
y.head()

SV
0  63.205396
1  63.503881
2  59.745951
3  61.829199
4  64.594981

In [310]:
print(x.shape)
print(y.shape)

(500, 10)
(500, 1)


#Break...intensionally left

#Test , Test Split


In [311]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=43)

In [312]:
"""
from google.colab import files
train_data.to_csv('train_data.csv')
test_data.download('test_data.csv')
"""

"\nfrom google.colab import files\ntrain_data.to_csv('train_data.csv')\ntest_data.download('test_data.csv')\n"

In [313]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(375, 10)
(375, 1)
(125, 10)
(125, 1)


#left intension

#Linear Regression

In [315]:
from sklearn import linear_model
model_linear = linear_model.LinearRegression()


In [316]:
model_linear.fit(x_train, y_train)

LinearRegression()

In [317]:
y_pred_linear = model_linear.predict(x_test)

In [318]:
y_pred_linear

array([[65.28293975],
       [65.01568328],
       [63.09761918],
       [62.31956569],
       [64.88878725],
       [65.93451171],
       [64.03973742],
       [64.34969169],
       [67.816089  ],
       [62.6674294 ],
       [64.42619104],
       [68.72236773],
       [64.68069335],
       [61.38699392],
       [64.08923999],
       [63.54661153],
       [62.97301712],
       [64.46621154],
       [65.66336643],
       [66.2514428 ],
       [61.83725987],
       [65.97940966],
       [63.8551082 ],
       [62.25874749],
       [65.39121711],
       [61.51391631],
       [62.89902667],
       [62.43121841],
       [62.37225871],
       [67.06547723],
       [60.97279414],
       [65.16595743],
       [61.43978363],
       [60.56465897],
       [62.59212135],
       [68.58202435],
       [63.75771073],
       [65.62778972],
       [64.1991922 ],
       [64.57503217],
       [65.64082631],
       [64.18665467],
       [66.67135818],
       [65.10459536],
       [62.70233251],
       [64

In [319]:
print(y_pred_linear.shape)

(125, 1)


In [320]:
#score Model

In [321]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

In [322]:
print("Mean Absolute Error is : {}".format( mean_absolute_error(y_test,y_pred_linear) ) )

print("Root Mean Squared Error is : {} ".format(np.sqrt(mean_squared_error(y_test,y_pred_linear))))

Mean Absolute Error is : 1.8150699595243287
Root Mean Squared Error is : 2.1777202803711146 


#AdaBoost


In [323]:
from sklearn.ensemble import AdaBoostRegressor

In [324]:
model_adaBoost = AdaBoostRegressor()

In [325]:
model_adaBoost.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AdaBoostRegressor()

In [326]:
y_pred_adaBoost = model_adaBoost.predict(x_test)

In [327]:
y_pred_adaBoost

array([63.03990395, 64.85862884, 63.34717522, 63.3742988 , 64.23422854,
       64.78388795, 65.01905069, 63.96415568, 69.16044622, 64.48896658,
       63.89524554, 66.52117009, 62.87602484, 64.05826235, 64.88317566,
       64.13237918, 62.83561255, 63.81387714, 64.23422854, 66.56707896,
       62.58341404, 64.91294248, 66.48405662, 64.23422854, 65.83805224,
       65.58769656, 63.59099639, 62.83561255, 63.32916117, 66.56707896,
       63.96415568, 63.96415568, 61.50113554, 63.89524554, 63.22826145,
       66.66515192, 63.00517396, 65.93337115, 64.38659689, 65.93337115,
       67.22456192, 63.47521289, 66.34420163, 62.68123649, 64.45940042,
       64.13237918, 62.87602484, 62.83561255, 66.79150327, 62.32789666,
       61.90404137, 62.52258544, 64.23422854, 62.58341404, 64.48896658,
       63.16330407, 63.61924437, 64.86929756, 64.23422854, 63.22826145,
       62.58341404, 63.96415568, 62.62509883, 64.57933741, 62.05350651,
       63.96415568, 63.96415568, 63.61924437, 64.38659689, 64.91

In [328]:
print( "Mean Absolute Error is : {}".format(mean_absolute_error(y_test,y_pred_adaBoost) ) )

print("Root Mean Squared Error is : {} ".format(np.sqrt(mean_squared_error(y_test,y_pred_adaBoost))))

Mean Absolute Error is : 2.1629719576874877
Root Mean Squared Error is : 2.600318294663275 


#Gradient Boost


In [287]:
from sklearn.ensemble import GradientBoostingRegressor

In [288]:
model_gradient = GradientBoostingRegressor(random_state = 0)

In [289]:
model_gradient.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GradientBoostingRegressor(random_state=0)

In [290]:
y_pred_gradient = model_gradient.predict(x_test)

In [291]:
y_pred_gradient

array([63.08885016, 63.8700267 , 64.09790983, ..., 66.40528117,
       64.6372105 , 60.95481508])

In [292]:
y_pred_gradient

array([63.08885016, 63.8700267 , 64.09790983, ..., 66.40528117,
       64.6372105 , 60.95481508])

In [293]:
print( "Mean Absolute Error is : {}".format(mean_absolute_error(y_test,y_pred_gradient) ) )

print("Root Mean Squared Error is : {} ".format(np.sqrt(mean_squared_error(y_test,y_pred_gradient))))

Mean Absolute Error is : 1.9600932561237554
Root Mean Squared Error is : 2.4033624531142346 
