#uploading

In [ ]:
#upload to the G-Drive
from google.colab import drive
drive.mount('/content/gdrive')

In [ ]:
import pandas as pd
df = pd.read_csv('/content/gdrive/My Drive/Project/basic models/GaussianCopula_dataset.csv')
df.shape

(400, 14)

In [ ]:
df.head()

Unnamed: 0  Sr.NO.  I.D      IPG       Peak    Valley     Der_1    Peak_1  \
0           0       3  D73  0.417455  0.776372  0.017887 -0.005329  0.075002   
1           1       8  D81  0.409211  0.775236  0.019488 -0.000346  0.076016   
2           2       6  D76  0.323571  0.641938  0.018008 -0.003104  0.074959   
3           3       9  D82  0.406211  0.775394  0.018121 -0.003051  0.073855   
4           4       4  D74  0.360704  0.767074  0.016122 -0.003988  0.074072   

   Valley_1     Der_2    Peak_2  Valley_2  LVET         SV  
0 -0.069028 -0.000417  0.026851 -0.016366    40  65.270261  
1 -0.066467 -0.000298  0.026231 -0.018566    40  65.278819  
2 -0.067352 -0.000428  0.025684 -0.017657    50  64.904144  
3 -0.066712 -0.000243  0.025935 -0.016661    40  64.674453  
4 -0.064596 -0.000500  0.025597 -0.017250    40  64.645219

In [ ]:
x = df.drop(["Unnamed: 0","Sr.NO.","I.D","SV"],axis=1)

In [ ]:
x.head()

IPG       Peak    Valley     Der_1    Peak_1  Valley_1     Der_2  \
0  0.417455  0.776372  0.017887 -0.005329  0.075002 -0.069028 -0.000417   
1  0.409211  0.775236  0.019488 -0.000346  0.076016 -0.066467 -0.000298   
2  0.323571  0.641938  0.018008 -0.003104  0.074959 -0.067352 -0.000428   
3  0.406211  0.775394  0.018121 -0.003051  0.073855 -0.066712 -0.000243   
4  0.360704  0.767074  0.016122 -0.003988  0.074072 -0.064596 -0.000500   

     Peak_2  Valley_2  LVET  
0  0.026851 -0.016366    40  
1  0.026231 -0.018566    40  
2  0.025684 -0.017657    50  
3  0.025935 -0.016661    40  
4  0.025597 -0.017250    40

In [ ]:
y = df[["SV"]]

In [ ]:
y.head()

SV
0  65.270261
1  65.278819
2  64.904144
3  64.674453
4  64.645219

#Test , Test Split


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=43)

In [ ]:
"""
from google.colab import files
train_data.to_csv('train_data.csv')
test_data.download('test_data.csv')
"""

"\nfrom google.colab import files\ntrain_data.to_csv('train_data.csv')\ntest_data.download('test_data.csv')\n"

In [ ]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(300, 10)
(300, 1)
(100, 10)
(100, 1)


#Linear Regression --- > Multiple

In [ ]:
from sklearn import linear_model

model_linear = linear_model.LinearRegression()
model_linear.fit(x_train, y_train)

LinearRegression()

In [ ]:
y_pred_linear = model_linear.predict(x_test)

In [ ]:
y_pred_linear

array([[64.90021378],
       [65.41557623],
       [63.58668597],
       [65.70408043],
       [65.23875144],
       [63.6872092 ],
       [65.36082811],
       [65.38192401],
       [65.35527144],
       [65.42888203],
       [64.99100544],
       [63.92198397],
       [63.46463438],
       [65.29490625],
       [64.30147662],
       [64.39979952],
       [65.28970413],
       [63.59133097],
       [65.09853456],
       [65.21158274],
       [64.77204387],
       [65.24042495],
       [65.1717835 ],
       [65.20687079],
       [65.57389743],
       [64.78249616],
       [64.48495515],
       [65.01351734],
       [64.92767085],
       [65.4525264 ],
       [64.29539122],
       [64.92533399],
       [65.25377707],
       [64.21415839],
       [65.23345077],
       [65.27546592],
       [64.28254356],
       [65.11722096],
       [65.0389553 ],
       [64.87102515],
       [64.51914674],
       [65.04510565],
       [63.82914591],
       [65.32699344],
       [65.08069416],
       [65

#AdaBoost


In [ ]:
from sklearn.ensemble import AdaBoostRegressor

In [ ]:
model_adaBoost = AdaBoostRegressor()

In [ ]:
model_adaBoost.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AdaBoostRegressor()

In [ ]:
y_pred_adaBoost = model_adaBoost.predict(x_test)

In [ ]:
y_pred_adaBoost

array([64.61655335, 65.47547894, 63.95675361, 65.58239901, 64.95830523,
       63.96018107, 65.52253912, 64.95429336, 65.23364276, 65.52373121,
       64.3064339 , 63.97008508, 63.88417516, 65.30869696, 64.18561395,
       64.12861875, 64.51659648, 63.95675361, 64.97869906, 65.50230087,
       64.33893244, 65.41333195, 65.35686737, 65.50350107, 65.57326328,
       64.36454268, 64.30506107, 65.01137263, 65.27309956, 65.57326328,
       64.18932021, 64.97869906, 65.21276155, 64.07477465, 65.01745174,
       65.52253912, 64.263921  , 65.06923696, 65.41333195, 64.50444375,
       64.24831921, 64.85154581, 63.97877254, 65.54056179, 65.20385115,
       65.21286352, 65.04367912, 64.95830523, 64.50140728, 64.41402876,
       64.44779949, 64.18561395, 65.36125847, 64.98619536, 65.57326328,
       65.46848153, 65.57326328, 64.70587751, 64.19007087, 64.4060658 ,
       65.52373121, 64.36454268, 64.91843724, 63.7075776 , 65.23132859,
       65.32353613, 64.80765892, 65.50350107, 64.09015868, 64.95

#MLP

In [ ]:
#import matplotlib.pyplot as plt 
import numpy as np
import pandas as pd
import seaborn as sns
from numpy.linalg import inv
import time
#import plotly.graph_objects as go
#import plotly.express as px
from sklearn.neural_network import MLPRegressor


In [ ]:
model_MLP = MLPRegressor(random_state=1, max_iter=3000).fit(x_train, y_train)
#regr = MLPRegressor(random_state=1, max_iter=3000,hidden_layer_sizes=(5,3)).fit(x_train, y_train)
print('The R2 score of our prediction is %.4f' %(model_MLP.score(x_test, y_test)))

y_pred_MLP = model_MLP.predict(x_test)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1599: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


The R2 score of our prediction is -0.4335


In [ ]:
y_pred_MLP

array([64.69926586, 65.25741001, 64.38983544, 65.417175  , 65.41601941,
       65.22019271, 65.2434121 , 65.26056585, 65.47401854, 65.41948223,
       63.80639135, 64.70823859, 62.89026838, 65.39938899, 64.24686865,
       65.01632913, 63.83187767, 63.53377036, 64.63733189, 65.36793256,
       63.40109467, 65.38193766, 64.87004864, 65.0965725 , 65.4901718 ,
       64.40705979, 64.1470455 , 64.50549421, 63.62938728, 65.48106635,
       64.15112089, 65.37282496, 65.43501853, 64.03857215, 65.41899131,
       65.36465936, 64.76261143, 65.43139758, 65.52871759, 64.16209495,
       64.87803183, 64.34130156, 64.66721487, 65.42011806, 65.32102373,
       65.4829677 , 65.37320834, 65.22572541, 64.46667941, 64.64765344,
       64.79850766, 64.13182325, 65.52938743, 63.23519821, 65.44647241,
       63.97115627, 65.47005087, 64.60984075, 64.49981857, 65.38224329,
       64.13641628, 64.44716149, 64.99092622, 63.19750217, 65.19189922,
       65.10263634, 64.04276318, 65.34664583, 64.51891735, 65.45

# Hybrid


In [ ]:
from mlxtend.regressor import StackingRegressor
from sklearn.svm import SVR

In [ ]:
regressors = [model_linear, model_adaBoost, model_MLP]
# regressors = [model_lr, model_nnr]
svr_rbf = SVR(kernel = 'rbf')

stregr = StackingRegressor(
    regressors = regressors, 
    meta_regressor = svr_rbf
).fit(x_train, y_train)

pred_stack = stregr.predict(x_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1599: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
pred_stack

array([64.64797618, 65.58235018, 63.85936366, 65.69711393, 64.85606737,
       63.76903187, 65.7262912 , 64.8656124 , 65.18527017, 65.64138235,
       64.61438684, 63.9527277 , 63.63002569, 65.33955856, 64.30997795,
       64.13509755, 64.73270198, 63.75588654, 64.79972742, 65.60610858,
       64.6146742 , 65.47465044, 65.32845525, 65.51776473, 65.63323868,
       64.44424704, 64.47138406, 64.97876443, 65.19376649, 65.72367807,
       64.36553002, 64.92887552, 65.30628429, 64.2612421 , 65.08646071,
       65.64993932, 64.3114833 , 65.13499756, 65.50871728, 64.62503755,
       64.27681075, 64.85085321, 63.98511073, 65.71370926, 65.19825481,
       65.25819696, 65.18589754, 64.8806133 , 64.51219355, 64.45655395,
       64.47484644, 64.24975862, 65.42827582, 65.20741717, 65.71120436,
       65.35087727, 65.71777669, 64.7617456 , 64.29522814, 64.31028045,
       65.42859055, 64.4402627 , 64.73477982, 63.54544864, 65.24228517,
       65.4199016 , 64.87337747, 65.47190417, 64.11614297, 64.95

#Error Metrics

In [ ]:
import numpy as np

In [ ]:
print( "Mean Absolute Error is : {}".format(mean_absolute_error(y_test,pred_stack) ) )

print("Root Mean Squared Error is : {} ".format(np.sqrt(mean_squared_error(y_test,pred_stack))))

Mean Absolute Error is : 1.9600932561237554
Root Mean Squared Error is : 2.4033624531142346 


In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

In [ ]:
print("Mean Absolute Error is : ")
mean_absolute_error(y_test,pred_stack)

Mean Absolute Error is : 


0.20005097178596948

In [ ]:
print("Mean Squared Error is ")
mean_squared_error(y_test,pred_stack)

Mean Squared Error is 


0.06603956129856738

In [ ]:
print("Root Mean Squared Error is ")
np.sqrt(mean_squared_error(y_test,pred_stack))

Root Mean Squared Error is 


0.2569816361115467